apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-local-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ishan/kube-data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi