---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
data:
  start.sh: |-
    #!/bin/bash
    export SOLR_HOST=${HOSTNAME}.solr.default.svc.cluster.local
    export SOLR_HOME=/data/data/${HOSTNAME}
    export SOLR_LOGS_DIR=/data/logs/${HOSTNAME}
    cp /opt/solr/dist/solr-jaegertracer-configurator-*.jar /opt/solr/server/solr-webapp/webapp/WEB-INF/lib
    cp /opt/solr/contrib/jaegertracer-configurator/lib/*.jar /opt/solr/server/solr-webapp/webapp/WEB-INF/lib
    /opt/solr/bin/solr -c -f -force

  solr.xml: |-
    <solr>
      <int name="maxBooleanClauses">${solr.max.booleanClauses:1024}</int>
      <solrcloud>
        <str name="host">${host:}</str>
        <int name="hostPort">${jetty.port:8983}</int>
        <str name="hostContext">${hostContext:solr}</str>
        <bool name="genericCoreNodeNames">${genericCoreNodeNames:true}</bool>
        <int name="zkClientTimeout">${zkClientTimeout:30000}</int>
        <int name="distribUpdateSoTimeout">${distribUpdateSoTimeout:600000}</int>
        <int name="distribUpdateConnTimeout">${distribUpdateConnTimeout:60000}</int>
        <str name="zkCredentialsProvider">${zkCredentialsProvider:org.apache.solr.common.cloud.DefaultZkCredentialsProvider}</str>
        <str name="zkACLProvider">${zkACLProvider:org.apache.solr.common.cloud.DefaultZkACLProvider}</str>
      </solrcloud>
      <shardHandlerFactory name="shardHandlerFactory"
        class="HttpShardHandlerFactory">
        <int name="socketTimeout">${socketTimeout:600000}</int>
        <int name="connTimeout">${connTimeout:60000}</int>
        <str name="shardsWhitelist">${solr.shardsWhitelist:}</str>
      </shardHandlerFactory>
      <tracerConfig name="tracerConfig" class="org.apache.solr.jaeger.JaegerTracerConfigurator">
        <str name="agentHost">jaeger-agent</str>
        <int name="agentPort">5775</int>
        <bool name="logSpans">true</bool>
        <int name="flushInterval">1000</int>
        <int name="maxQueueSize">10000</int>
      </tracerConfig>
    </solr>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
spec:
  selector:
    matchLabels:
      app: solr-app # has to match .spec.template.metadata.labels
  serviceName: solr
  replicas: 3
  template:
    metadata:
      labels:
        app: solr-app # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: volsolr
        persistentVolumeClaim:
          claimName: solr-pv-claim
      - name: configs-volume
        configMap:
          defaultMode: 0700
          name: configs
      containers:
      - name: solr
        image: searchstack/solr:8.2
        volumeMounts:
        - name: configs-volume
          mountPath: /etc/config
        - name: volsolr
          mountPath: /data
        ports:
        - name: solr-port
          containerPort: 8983
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          httpGet:
            scheme: "HTTP"
            path: /solr/admin/info/health
            port: 8983
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          httpGet:
            scheme: "HTTP"
            path: /solr/admin/info/health
            port: 8983
        env:
          - name: SOLR_PORT
            value: "8983"
          - name: ZK_HOST
            value: "zookeeper-service:2181"
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command:
          - /data/start-solr.sh
      initContainers:
      - name: init-solr-data
        image: busybox
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command: ['sh', '-c', 'mkdir -p /data/data/${HOSTNAME} && chown 8983:8983 /data/data/$HOSTNAME; mkdir -p /data/logs && chown 8983:8983 /data/logs']
        volumeMounts:
        - name: volsolr
          mountPath: /data
      - name: init-solr-xml
        image: busybox
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name                         
        command: ['sh', '-c', 'cp /etc/config/solr.xml /data/data/${HOSTNAME}/solr.xml; chmod 777 /data/data/${HOSTNAME}/solr.xml; cp /etc/config/start.sh /data/start-solr.sh; chmod 777 /data/start-solr.sh']
        volumeMounts:
        - name: volsolr
          mountPath: /data
        - name: configs-volume
          mountPath: /etc/config
---
# Headless service
apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  ports:
  - port: 8983
  clusterIP: None
  selector:
    app: solr-app

---
# External Service used to access external endpoint
apiVersion: v1
kind: Service
metadata:
    name: solr-svc-public
spec:
    type: LoadBalancer
    ports:
      - port: 8983
        targetPort: client
    selector:
        app: solr-app

---
# Internal service, which other Pods can connect with
apiVersion: v1
kind: Service
metadata:
  name: solr-service
spec:
  ports:
  - port: 8983
    targetPort: 8983
    nodePort: 30983
    protocol: TCP
  selector:
    app: solr-app
  type: NodePort
